version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  bot:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: npm run dev
    container_name: bot
    volumes:
      - "./app:${DOCKER_PATH}/app"
      - "${DOCKER_PATH}/app/node_modules"
    depends_on:
      - mongodb
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      FASTREPORT_API_TOKEN: ${FASTREPORT_API_TOKEN}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

